/* 作成履歴                                                    */
/* Ｎｏ   修正日付   修正者     修正内容                       */
/*   1  2026/01/07  k.takashima LMDC移行対応：不要資産TABLE削除*/
DROP TABLE DT緊急カット商品;
DROP TABLE DT緊急カット入力対象商品;
DROP TABLE DT返品モニタリング;
DROP TABLE DT返品削減計画終了対象商品;
DROP TABLE HNP_くくりベンダーパラメータ;
DROP TABLE HNP_返品削減コカパラメータ;
DROP TABLE HNP_返品削減除外パラメータ;
DROP TABLE HNP_返品削減新宛先パラメータ;
DROP TABLE HNT_エリアＳＫＵ;
DROP TABLE HNT_サマリ発注データ;
DROP TABLE HNT_メーカー;
DROP TABLE HNT_宛先ＷＥＢＥＤＩ情報;
DROP TABLE HNT_取引先商品別入出残累積;
DROP TABLE HNT_商品;
DROP TABLE HNT_商品ＤＩＶ;
DROP TABLE HNT_推奨取消商品案内;
DROP TABLE HNT_入荷確定累積;
DROP TABLE HNT_ＣＬＡＳＳ返品モニタ用;
DROP TABLE HNW_ＷＥＢＥＤＩデータ;
DROP TABLE HNW_エリアＳＫＵ;
DROP TABLE HNW_エリアＳＫＵ物流;
DROP TABLE HNW_くくりベンダーサマリ発注数;
DROP TABLE HNW_緊急カット商品;
DROP TABLE HNW_緊急カット入力対象商品;
DROP TABLE HNW_計画終了商品;
DROP TABLE HNW_在庫切れデータ;
DROP TABLE HNW_商品ベンダー;
DROP TABLE HNW_商品ベンダー宛先;
DROP TABLE HNW_商品返品くくりベンダー;
DROP TABLE HNW_商返品くくりベンダー在庫数;
DROP TABLE HNW_推奨取消商品;
DROP TABLE HNW_対象ＤＤＣ商品;
DROP TABLE HNW_返品モニタリング;
DROP TABLE HNW_返品削減計画終了対象商品;
DROP TABLE HNW_地域別商品年度週ＮＯ;
DROP TABLE HNW_商品ベンダー年度週ＮＯ;
