LOAD DATA
 APPEND INTO TABLE HNT_ベンダー別商品
 (
 商品コード                               POSITION(1:13) CHAR,
 ベンダーコード                           POSITION(14:19) CHAR,
 有効終了日                               POSITION(20:27) DATE 'YYYYMMDD',
 有効開始日                               POSITION(28:35) DATE 'YYYYMMDD',
 初回有効開始日                           POSITION(36:43) DATE 'YYYYMMDD',
 社コード                                 POSITION(44:49) CHAR,
 通常原価本体金額                         POSITION(50:57) ZONED(8,2) NULLIF 通常原価本体金額=BLANKS,
 通常原価税込金額                         POSITION(58:65) ZONED(8,2) NULLIF 通常原価税込金額=BLANKS,
 通常原価税金額                           POSITION(66:73) ZONED(8,2) NULLIF 通常原価税金額=BLANKS,
 通常売価本体金額                         POSITION(74:79) ZONED NULLIF 通常売価本体金額=BLANKS,
 通常売価税込金額                         POSITION(80:85) ZONED NULLIF 通常売価税込金額=BLANKS,
 通常売価税金額                           POSITION(86:91) ZONED NULLIF 通常売価税金額=BLANKS,
 原価本体金額                             POSITION(92:99) ZONED(8,2) NULLIF 原価本体金額=BLANKS,
 原価税込金額                             POSITION(100:107) ZONED(8,2) NULLIF 原価税込金額=BLANKS,
 原価税金額                               POSITION(108:115) ZONED(8,2) NULLIF 原価税金額=BLANKS,
 売価本体金額                             POSITION(116:121) ZONED NULLIF 売価本体金額=BLANKS,
 売価税込金額                             POSITION(122:127) ZONED NULLIF 売価税込金額=BLANKS,
 売価税金額                               POSITION(128:133) ZONED NULLIF 売価税金額=BLANKS,
 原価条件取得フラグ                       POSITION(134:135) CHAR,
 原価条件取得開始日                       POSITION(136:143) DATE 'YYYYMMDD',
 原価条件取得終了日                       POSITION(144:151) DATE 'YYYYMMDD',
 最低発注数                               POSITION(152:156) ZONED NULLIF 最低発注数=BLANKS,
 追加発注数                               POSITION(157:161) ZONED NULLIF 追加発注数=BLANKS,
 最大発注数                               POSITION(162:166) ZONED NULLIF 最大発注数=BLANKS,
 新店発注数                               POSITION(167:171) ZONED NULLIF 新店発注数=BLANKS,
 発注終了日                               POSITION(172:179) DATE 'YYYYMMDD',
 商品格付区分                             POSITION(180:181) CHAR,
 新商品フラグ                             POSITION(182:183) CHAR,
 基本商品フラグ                           POSITION(184:185) CHAR,
 商品案内対象区分                         POSITION(186:187) CHAR,
 店取状況リセットフラグ                   POSITION(188:189) CHAR,
 一時カットフラグ                         POSITION(190:191) CHAR,
 返品不可区分                             POSITION(192:193) CHAR,
 日販即売雑誌返品先区分                   POSITION(194:195) CHAR,
 沖縄即売雑誌返品先区分                   POSITION(196:197) CHAR,
 ケースラベル区分                         POSITION(198:199) CHAR,
 シェル商品コード                         POSITION(200:212) CHAR,
 入荷許容期間基準区分                     POSITION(213:214) CHAR,
 入荷許容期間年月日区分                   POSITION(215:216) CHAR,
 入荷許容期間                             POSITION(217:219) ZONED NULLIF 入荷許容期間=BLANKS,
 販売許容期間基準区分                     POSITION(220:221) CHAR,
 販売許容期間年月日区分                   POSITION(222:223) CHAR,
 販売許容期間                             POSITION(224:226) ZONED NULLIF 販売許容期間=BLANKS,
 変更取消理由区分                         POSITION(227:228) CHAR,
 変更取消備考                             POSITION(229:248) CHAR,
 販売実績数                               POSITION(249:254) ZONED(6,2) NULLIF 販売実績数=BLANKS,
 ＳＵＢ平均数                             POSITION(255:260) ZONED(6,2) NULLIF ＳＵＢ平均数=BLANKS,
 会計取引先コード                         POSITION(261:266) CHAR,
 会計取引先名                             POSITION(267:296) CHAR,
 納品ＬＴ日数                             POSITION(297:298) ZONED NULLIF 納品ＬＴ日数=BLANKS,
 ＰＯＰ区分                               POSITION(299:300) CHAR,
 ＰＯＰデザイン区分                       POSITION(301:302) CHAR,
 ＰＯＰ形状区分                           POSITION(303:304) CHAR,
 ＰＯＰ請求先区分                         POSITION(305:306) CHAR,
 ＰＯＰ当店通常金額                       POSITION(307:313) ZONED NULLIF ＰＯＰ当店通常金額=BLANKS,
 ＰＯＰ会員割引金額                       POSITION(314:320) ZONED NULLIF ＰＯＰ会員割引金額=BLANKS,
 ＰＯＰメーカー名                         POSITION(321:342) CHAR,
 ＰＯＰ商品名                             POSITION(343:386) CHAR,
 ＰＯＰ規格名                             POSITION(387:408) CHAR,
 ＰＯＰセールスポイント説明               POSITION(409:452) CHAR,
 ＰＯＰ掲出期間開始日                     POSITION(453:460) DATE 'YYYYMMDD',
 ＰＯＰ掲出期間終了日                     POSITION(461:468) DATE 'YYYYMMDD',
 エリア拡大回数                           POSITION(469:469) ZONED NULLIF エリア拡大回数=BLANKS,
 初回導入条件                             POSITION(470:509) CHAR,
 変更取消理由説明                         POSITION(510:539) CHAR,
 マルチメディア共通管理１                 POSITION(540:549) ZONED NULLIF マルチメディア共通管理１=BLANKS,
 マルチメディア共通管理２                 POSITION(550:559) ZONED NULLIF マルチメディア共通管理２=BLANKS,
 商談採用情報確認フラグ                   POSITION(560:561) CHAR,
 入力依頼者氏名コード                     POSITION(562:569) CHAR,
 入力依頼者氏名                           POSITION(570:589) CHAR,
 処理区分                                 POSITION(590:591) CHAR,
 物理削除日                               POSITION(592:599) DATE 'YYYYMMDD',
 コピー処理日                             POSITION(600:607) DATE 'YYYYMMDD',
 コピー処理状況区分                       POSITION(608:609) CHAR,
 物理削除区分                             POSITION(610:611) CHAR,
 作成者氏名コード                         POSITION(612:619) CHAR,
 作成者氏名                               POSITION(620:649) CHAR,
 作成者部署コード                         POSITION(650:655) CHAR,
 作成者部署名                             POSITION(656:695) CHAR,
 作成プログラムＩＤ                       POSITION(696:735) CHAR,
 作成日時                                 POSITION(736:749) DATE "YYYYMMDDHH24MISS",
 オンライン更新者氏名コード               POSITION(750:757) CHAR,
 オンライン更新者氏名                     POSITION(758:787) CHAR,
 オンライン更新者部署コード               POSITION(788:793) CHAR,
 オンライン更新者部署名                   POSITION(794:833) CHAR,
 オンライン更新プログラムＩＤ             POSITION(834:873) CHAR,
 オンライン更新日時                       POSITION(874:887) DATE "YYYYMMDDHH24MISS",
 バッチ更新プログラムＩＤ                 POSITION(888:927) CHAR,
 バッチ更新日時                           POSITION(928:941) DATE "YYYYMMDDHH24MISS",
 ロック連番                               POSITION(942:945) ZONED NULLIF ロック連番=BLANKS,
 削除区分                                 POSITION(946:947) CHAR,
 更新端末ＩＤ                             POSITION(948:977) CHAR
 )
