LOAD DATA
 APPEND INTO TABLE HNT_ＤＥＰＴ
 (
 社コード                                 POSITION(1:6) CHAR,
 ＤＥＰＴコード                           POSITION(7:9) CHAR,
 有効終了日                               POSITION(10:17) DATE "YYYYMMDD",
 有効開始日                               POSITION(18:25) DATE "YYYYMMDD",
 ＤＥＰＴ名                               POSITION(26:75) CHAR
  "DECODE(RTRIM(RTRIM(:ＤＥＰＴ名),'　'),NULL,'　',RTRIM(RTRIM(:ＤＥＰＴ名),'　'))",
 ＤＥＰＴ名カナ                           POSITION(76:100) CHAR
  "DECODE(RTRIM(RTRIM(:ＤＥＰＴ名カナ),'　'),NULL,'　',RTRIM(RTRIM(:ＤＥＰＴ名カナ),'　'))",
 商品ＤＩＶコード                         POSITION(101:103) CHAR,
 品目コード                               POSITION(104:105) CHAR,
 ＦＦ商品識別フラグ                       POSITION(106:107) CHAR,
 売上集計区分                             POSITION(108:109) CHAR,
 ＡＢＣ分析区分                           POSITION(110:111) CHAR,
 単品動向表示フラグ                       POSITION(112:113) CHAR,
 販売率計算区分                           POSITION(114:115) CHAR,
 販売動向表示区分                         POSITION(116:117) CHAR,
 外税商品コード                           POSITION(118:130) CHAR,
 内税商品コード                           POSITION(131:143) CHAR,
 非課税商品コード                         POSITION(144:156) CHAR,
 不課税商品コード                         POSITION(157:169) CHAR,
 受託品フラグ                             POSITION(170:171) CHAR,
 目標設定区分                             POSITION(172:173) CHAR,
 原材料棚卸フラグ                         POSITION(174:175) CHAR,
 入力依頼者氏名コード                     POSITION(176:183) CHAR,
 入力依頼者氏名                           POSITION(184:203) CHAR,
 処理区分                                 POSITION(204:205) CHAR,
 コピー処理日                             POSITION(206:213) DATE "YYYYMMDD",
 コピー処理状況区分                       POSITION(214:215) CHAR,
 作成者氏名コード                         POSITION(216:223) CHAR,
 作成者氏名                               POSITION(224:253) CHAR,
 作成者部署コード                         POSITION(254:259) CHAR,
 作成者部署名                             POSITION(260:299) CHAR,
 作成プログラムＩＤ                       POSITION(300:339) CHAR,
 作成日時                                 POSITION(340:353) DATE "YYYYMMDDHH24MISS",
 オンライン更新者氏名コード               POSITION(354:361) CHAR,
 オンライン更新者氏名                     POSITION(362:391) CHAR,
 オンライン更新者部署コード               POSITION(392:397) CHAR,
 オンライン更新者部署名                   POSITION(398:437) CHAR,
 オンライン更新プログラムＩＤ             POSITION(438:477) CHAR,
 オンライン更新日時                       POSITION(478:491) DATE "YYYYMMDDHH24MISS",
 バッチ更新プログラムＩＤ                 POSITION(492:531) CHAR,
 バッチ更新日時                           POSITION(532:545) DATE "YYYYMMDDHH24MISS",
 ロック連番                               POSITION(546:549) ZONED NULLIF ロック連番=BLANKS,
 削除区分                                 POSITION(550:551) CHAR,
 更新端末ＩＤ                             POSITION(552:581) CHAR
 )
