LOAD DATA
 APPEND INTO TABLE HNT_新オンライン宛先基本情報
 (
 チェーンストアコード                     POSITION(1:4) CHAR,
 宛先コード                               POSITION(5:12) CHAR,
 有効終了日                               POSITION(13:20) DATE "YYYYMMDD",
 有効開始日                               POSITION(21:28) DATE "YYYYMMDD",
 社コード                                 POSITION(29:34) CHAR,
 収納代行フラグ                           POSITION(35:36) CHAR,
 ＣＬチェーンストアコード                 POSITION(37:40) CHAR,
 ケースラベル宛先コード                   POSITION(41:48) CHAR,
 コピーフラグ                             POSITION(49:50) CHAR,
 宛先名カナ                               POSITION(51:75) CHAR
  "DECODE(RTRIM(RTRIM(:宛先名カナ),' '),NULL,' ',RTRIM(RTRIM(:宛先名カナ),' '))",
 宛先名                                   POSITION(76:125) CHAR
  "DECODE(RTRIM(RTRIM(:宛先名),'　'),NULL,'　',RTRIM(RTRIM(:宛先名),'　'))",
 担当者氏名カナ                           POSITION(126:150) CHAR
  "DECODE(RTRIM(RTRIM(:担当者氏名カナ),' '),NULL,' ',RTRIM(RTRIM(:担当者氏名カナ),' '))",
 担当者氏名                               POSITION(151:200) CHAR
  "DECODE(RTRIM(RTRIM(:担当者氏名),'　'),NULL,'　',RTRIM(RTRIM(:担当者氏名),'　'))",
 連絡先市外局番                           POSITION(201:208) CHAR,
 連絡先市内局番                           POSITION(209:212) CHAR,
 連絡先個別番号                           POSITION(213:216) CHAR,
 宛先ＦＡＸ市外局番                       POSITION(217:224) CHAR,
 宛先ＦＡＸ市内局番                       POSITION(225:228) CHAR,
 宛先ＦＡＸ個別番号                       POSITION(229:232) CHAR,
 発信先電話市外局番                       POSITION(233:240) CHAR,
 発信先電話市内局番                       POSITION(241:244) CHAR,
 発信先電話個別番号                       POSITION(245:248) CHAR,
 ソフト会社電話市外局番                   POSITION(249:256) CHAR,
 ソフト会社電話市内局番                   POSITION(257:260) CHAR,
 ソフト会社電話個別番号                   POSITION(261:264) CHAR,
 取引先コード                             POSITION(265:271) CHAR,
 会社グループ名カナ                       POSITION(272:281) CHAR,
 郵便番号                                 POSITION(282:289) CHAR,
 オンライン宛先１住所                     POSITION(290:319) CHAR,
 オンライン宛先２住所                     POSITION(320:369) CHAR,
 オンライン宛先会社名                     POSITION(370:419) CHAR,
 オンライン宛先部署名                     POSITION(420:459) CHAR,
 ソフト会社名                             POSITION(460:509) CHAR,
 処理区分                                 POSITION(510:511) CHAR,
 物理削除日                               POSITION(512:519) DATE "YYYYMMDD",
 コピー処理日                             POSITION(520:527) DATE "YYYYMMDD",
 コピー処理状況区分                       POSITION(528:529) CHAR,
 物理削除区分                             POSITION(530:531) CHAR,
 作成者氏名コード                         POSITION(532:539) CHAR,
 作成者氏名                               POSITION(540:569) CHAR,
 作成者部署コード                         POSITION(570:575) CHAR,
 作成者部署名                             POSITION(576:615) CHAR,
 作成プログラムＩＤ                       POSITION(616:655) CHAR,
 作成日時                                 POSITION(656:669) DATE "YYYYMMDDHH24MISS",
 オンライン更新者氏名コード               POSITION(670:677) CHAR,
 オンライン更新者氏名                     POSITION(678:707) CHAR,
 オンライン更新者部署コード               POSITION(708:713) CHAR,
 オンライン更新者部署名                   POSITION(714:753) CHAR,
 オンライン更新プログラムＩＤ             POSITION(754:793) CHAR,
 オンライン更新日時                       POSITION(794:807) DATE "YYYYMMDDHH24MISS",
 バッチ更新プログラムＩＤ                 POSITION(808:847) CHAR,
 バッチ更新日時                           POSITION(848:861) DATE "YYYYMMDDHH24MISS",
 ロック連番                               POSITION(862:865) ZONED NULLIF ロック連番=BLANKS,
 削除区分                                 POSITION(866:867) CHAR,
 更新端末ＩＤ                             POSITION(868:897) CHAR
 )
