LOAD DATA
 APPEND INTO TABLE HNT_納品エリア
 (
 納品エリアコード                         POSITION(1:6) CHAR,
 有効終了日                               POSITION(7:14) DATE "YYYYMMDD",
 有効開始日                               POSITION(15:22) DATE "YYYYMMDD",
 納品エリア名                             POSITION(23:72) CHAR,
 社コード                                 POSITION(73:78) CHAR,
 商品部エリアコード                       POSITION(79:80) CHAR,
 商品部地域コード                         POSITION(81:83) CHAR,
 物流ロケーション区分                     POSITION(84:85) CHAR,
 掲載エリアコード                         POSITION(86:88) CHAR,
 ＣＤＣ１便ベンダーコード                 POSITION(89:94) CHAR,
 ＣＤＣ２便ベンダーコード                 POSITION(95:100) CHAR,
 ＣＤＣ３便ベンダーコード                 POSITION(101:106) CHAR,
 入荷明細ベンダーコード                   POSITION(107:112) CHAR,
 分割前納品エリアコード                   POSITION(113:118) CHAR,
 メニューキー地区コード                   POSITION(119:120) CHAR,
 入力依頼者氏名コード                     POSITION(121:128) CHAR,
 入力依頼者氏名                           POSITION(129:148) CHAR,
 処理区分                                 POSITION(149:150) CHAR,
 物理削除日                               POSITION(151:158) DATE "YYYYMMDD",
 コピー処理日                             POSITION(159:166) DATE "YYYYMMDD",
 コピー処理状況区分                       POSITION(167:168) CHAR,
 物理削除区分                             POSITION(169:170) CHAR,
 作成者氏名コード                         POSITION(171:178) CHAR,
 作成者氏名                               POSITION(179:208) CHAR,
 作成者部署コード                         POSITION(209:214) CHAR,
 作成者部署名                             POSITION(215:254) CHAR,
 作成プログラムＩＤ                       POSITION(255:294) CHAR,
 作成日時                                 POSITION(295:308) DATE "YYYYMMDDHH24MISS",
 オンライン更新者氏名コード               POSITION(309:316) CHAR,
 オンライン更新者氏名                     POSITION(317:346) CHAR,
 オンライン更新者部署コード               POSITION(347:352) CHAR,
 オンライン更新者部署名                   POSITION(353:392) CHAR,
 オンライン更新プログラムＩＤ             POSITION(393:432) CHAR,
 オンライン更新日時                       POSITION(433:446) DATE "YYYYMMDDHH24MISS",
 バッチ更新プログラムＩＤ                 POSITION(447:486) CHAR,
 バッチ更新日時                           POSITION(487:500) DATE "YYYYMMDDHH24MISS",
 ロック連番                               POSITION(501:504) ZONED NULLIF ロック連番=BLANKS,
 削除区分                                 POSITION(505:506) CHAR,
 更新端末ＩＤ                             POSITION(507:536) CHAR
 )
