LOAD DATA
 APPEND INTO TABLE HNT_ベンダー
 (
 ベンダーコード                           POSITION(1:6) CHAR,
 有効終了日                               POSITION(7:14) DATE "YYYYMMDD",
 有効開始日                               POSITION(15:22) DATE "YYYYMMDD",
 社コード                                 POSITION(23:28) CHAR,
 ベンダー名                               POSITION(29:78) CHAR
  "DECODE(RTRIM(RTRIM(:ベンダー名),'　'),NULL,'　',RTRIM(RTRIM(:ベンダー名),'　'))",
 ベンダー名カナ                           POSITION(79:103) CHAR
  "DECODE(RTRIM(RTRIM(:ベンダー名カナ),' '),NULL,' ',RTRIM(RTRIM(:ベンダー名カナ),' '))",
 ベンダー区分                             POSITION(104:105) CHAR,
 配送区分                                 POSITION(106:107) CHAR,
 配送形態区分                             POSITION(108:109) CHAR,
 配送センター区分                         POSITION(110:111) CHAR,
 営業区分                                 POSITION(112:113) CHAR,
 エリア変更フラグ                         POSITION(114:115) CHAR,
 店取引先指定区分                         POSITION(116:117) CHAR,
 発注ツール出力不可区分                   POSITION(118:119) CHAR,
 取引先コード                             POSITION(120:126) CHAR,
 代表物流センターベンダーコード           POSITION(127:132) CHAR,
 配送センターベンダーコード               POSITION(133:138) CHAR,
 物流センター納品フラグ                   POSITION(139:140) CHAR,
 総合出力帳票有効フラグ                   POSITION(141:142) CHAR,
 店ＳＫＵ出力帳票有効フラグ               POSITION(143:144) CHAR,
 ＳＫＵ店出力帳票有効フラグ               POSITION(145:146) CHAR,
 発注締時刻                               POSITION(147:150) CHAR,
 便区分                                   POSITION(151:152) CHAR,
 納品エリア一括変更フラグ                 POSITION(153:154) CHAR,
 ＰＣ色区分                               POSITION(155:156) CHAR,
 ベンダー階層コード                       POSITION(157:162) CHAR,
 品揃取扱区分                             POSITION(163:164) CHAR,
 ベーカリー直納区分                       POSITION(165:166) CHAR,
 宅配ギフト種別                           POSITION(167:168) CHAR,
 宅配ギフト対象期間開始日                 POSITION(169:176) DATE "YYYYMMDD",
 宅配ギフト対象期間終了日                 POSITION(177:184) DATE "YYYYMMDD",
 入力依頼者氏名コード                     POSITION(185:192) CHAR,
 入力依頼者氏名                           POSITION(193:212) CHAR,
 処理区分                                 POSITION(213:214) CHAR,
 物理削除日                               POSITION(215:222) DATE "YYYYMMDD",
 コピー処理日                             POSITION(223:230) DATE "YYYYMMDD",
 コピー処理状況区分                       POSITION(231:232) CHAR,
 物理削除区分                             POSITION(233:234) CHAR,
 作成者氏名コード                         POSITION(235:242) CHAR,
 作成者氏名                               POSITION(243:272) CHAR,
 作成者部署コード                         POSITION(273:278) CHAR,
 作成者部署名                             POSITION(279:318) CHAR,
 作成プログラムＩＤ                       POSITION(319:358) CHAR,
 作成日時                                 POSITION(359:372) DATE "YYYYMMDDHH24MISS",
 オンライン更新者氏名コード               POSITION(373:380) CHAR,
 オンライン更新者氏名                     POSITION(381:410) CHAR,
 オンライン更新者部署コード               POSITION(411:416) CHAR,
 オンライン更新者部署名                   POSITION(417:456) CHAR,
 オンライン更新プログラムＩＤ             POSITION(457:496) CHAR,
 オンライン更新日時                       POSITION(497:510) DATE "YYYYMMDDHH24MISS",
 バッチ更新プログラムＩＤ                 POSITION(511:550) CHAR,
 バッチ更新日時                           POSITION(551:564) DATE "YYYYMMDDHH24MISS",
 ロック連番                               POSITION(565:568) ZONED NULLIF ロック連番=BLANKS,
 削除区分                                 POSITION(569:570) CHAR,
 更新端末ＩＤ                             POSITION(571:600) CHAR
 )
