LOAD DATA
 APPEND INTO TABLE HNT_ＣＬＡＳＳ
 (
 社コード                                 POSITION(1:6) CHAR,
 ＤＥＰＴコード                           POSITION(7:9) CHAR,
 ＣＬＡＳＳコード                         POSITION(10:12) CHAR,
 有効終了日                               POSITION(13:20) DATE "YYYYMMDD",
 有効開始日                               POSITION(21:28) DATE "YYYYMMDD",
 ＣＬＡＳＳ名                             POSITION(29:78) CHAR
  "DECODE(RTRIM(RTRIM(:ＣＬＡＳＳ名),'　'),NULL,'　',RTRIM(RTRIM(:ＣＬＡＳＳ名),'　'))",
 ＣＬＡＳＳ名カナ                         POSITION(79:103) CHAR
  "DECODE(RTRIM(RTRIM(:ＣＬＡＳＳ名カナ),'　'),NULL,'　',RTRIM(RTRIM(:ＣＬＡＳＳ名カナ),'　'))",
 集計用ＤＥＰＴコード                     POSITION(104:106) CHAR,
 集計用ＣＬＡＳＳコード                   POSITION(107:109) CHAR,
 集計用ＣＬＡＳＳ名                       POSITION(110:159) CHAR,
 日配ＰＣ発注フラグ                       POSITION(160:161) CHAR,
 ＰＣ発注フラグ                           POSITION(162:163) CHAR,
 ＯＢ発注対象フラグ                       POSITION(164:165) CHAR,
 商品台帳フラグ                           POSITION(166:167) CHAR,
 日配棚無ＯＢフラグ                       POSITION(168:169) CHAR,
 自動発注フラグ                           POSITION(170:171) CHAR,
 包材発注フラグ                           POSITION(172:173) CHAR,
 食事系発注対象フラグ                     POSITION(174:175) CHAR,
 日配品発注対象フラグ                     POSITION(176:177) CHAR,
 ドライ発注対象フラグ                     POSITION(178:179) CHAR,
 ＦＦ発注フラグ                           POSITION(180:181) CHAR,
 タバコ発注フラグ                         POSITION(182:183) CHAR,
 修正発注フラグ                           POSITION(184:185) CHAR,
 障害時発注フラグ                         POSITION(186:187) CHAR,
 特別発注フラグ                           POSITION(188:189) CHAR,
 売上経過日数区分                         POSITION(190:191) CHAR,
 カット区分                               POSITION(192:193) CHAR,
 商品ＷＲレポート出力要否フラグ           POSITION(194:195) CHAR,
 重点フラグ                               POSITION(196:197) CHAR,
 削除日数                                 POSITION(198:200) ZONED NULLIF 削除日数=BLANKS,
 自社発行ＪＡＮ解放保留日数               POSITION(201:203) ZONED NULLIF 自社発行ＪＡＮ解放保留日数=BLANKS,
 帳票出力数                               POSITION(204:207) ZONED NULLIF 帳票出力数=BLANKS,
 ライセンス種別                           POSITION(208:209) CHAR,
 セット品構成対象フラグ                   POSITION(210:211) CHAR,
 品揃対象フラグ                           POSITION(212:213) CHAR,
 新食事系フラグ                           POSITION(214:215) CHAR,
 在庫振替区分                             POSITION(216:217) CHAR,
 廃業免除幅率                             POSITION(218:221) ZONED(4,1) NULLIF 廃業免除幅率=BLANKS,
 商品部区分                               POSITION(222:223) CHAR,
 営業区分                                 POSITION(224:225) CHAR,
 伸び数                                   POSITION(226:229) ZONED NULLIF 伸び数=BLANKS,
 代表有無フラグ                           POSITION(230:231) CHAR,
 延着負担区分                             POSITION(232:233) CHAR,
 事前確定商品フラグ                       POSITION(234:235) CHAR,
 在庫抽選発注商品フラグ                   POSITION(236:237) CHAR,
 販売許容チェックフラグ                   POSITION(238:239) CHAR,
 販売許容１便時刻                         POSITION(240:243) CHAR,
 販売許容２便時刻                         POSITION(244:247) CHAR,
 販売許容３便時刻                         POSITION(248:251) CHAR,
 販売許容１便チェック時間                 POSITION(252:254) ZONED NULLIF 販売許容１便チェック時間=BLANKS,
 販売許容２便チェック時間                 POSITION(255:257) ZONED NULLIF 販売許容２便チェック時間=BLANKS,
 販売許容３便チェック時間                 POSITION(258:260) ZONED NULLIF 販売許容３便チェック時間=BLANKS,
 標準ＳＫＵ数                             POSITION(261:263) ZONED NULLIF 標準ＳＫＵ数=BLANKS,
 消費税区分                               POSITION(264:265) CHAR,
 鮮度管理対象区分                         POSITION(266:267) CHAR,
 値引対象外フラグ                         POSITION(268:269) CHAR,
 気温補正フラグ                           POSITION(270:271) CHAR,
 計画終了対象フラグ                       POSITION(272:273) CHAR,
 入力依頼者氏名コード                     POSITION(274:281) CHAR,
 入力依頼者氏名                           POSITION(282:301) CHAR,
 処理区分                                 POSITION(302:303) CHAR,
 コピー処理日                             POSITION(304:311) DATE "YYYYMMDD",
 コピー処理状況区分                       POSITION(312:313) CHAR,
 作成者氏名コード                         POSITION(314:321) CHAR,
 作成者氏名                               POSITION(322:351) CHAR,
 作成者部署コード                         POSITION(352:357) CHAR,
 作成者部署名                             POSITION(358:397) CHAR,
 作成プログラムＩＤ                       POSITION(398:437) CHAR,
 作成日時                                 POSITION(438:451) DATE "YYYYMMDDHH24MISS",
 オンライン更新者氏名コード               POSITION(452:459) CHAR,
 オンライン更新者氏名                     POSITION(460:489) CHAR,
 オンライン更新者部署コード               POSITION(490:495) CHAR,
 オンライン更新者部署名                   POSITION(496:535) CHAR,
 オンライン更新プログラムＩＤ             POSITION(536:575) CHAR,
 オンライン更新日時                       POSITION(576:589) DATE "YYYYMMDDHH24MISS",
 バッチ更新プログラムＩＤ                 POSITION(590:629) CHAR,
 バッチ更新日時                           POSITION(630:643) DATE "YYYYMMDDHH24MISS",
 ロック連番                               POSITION(644:647) ZONED NULLIF ロック連番=BLANKS,
 削除区分                                 POSITION(648:649) CHAR,
 更新端末ＩＤ                             POSITION(650:679) CHAR
 )
