#_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
# 変数の定義
#_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
##
logd=${PROD_DIR}/LOG
semd=${PROD_DIR}/JOB_CTRL
shld=${PROD_DIR}/SHELL
tbld=${PROD_DIR}/HPSG/TBL
xlsd=${PROD_DIR}/HPSG/EXCEL
tpld=${PROD_DIR}/PRM/TEMPLATE
sendlogd=${PROD_DIR}/HPSG/SENDLOG
orad=${PROD_DIR}/DATA_HPSG
datad=${PROD_DIR}/DATA
tmp=${PROD_DIR}/tmp/$$

#_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
# メール関係
#_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
##
##
from=${hpsg_from}
return_path=${hpsg_return}
error_uketuke=${hpsg_error_uketuke}

##
##
##
##
##

