#_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
# 変数の定義
#_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
##
logd=${PROD_DIR}/LOG
semd=${PROD_DIR}/JOB_CTRL
sysd=${PROD_DIR}/SHELL
sqld=${PROD_DIR}/ORCL/SQL
orad=${PROD_DIR}/DATA_HPSG
tmp=${PROD_DIR}/tmp/$$

#_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
# オラクル関係の定義
#_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
LANG=ja_JP.UTF-8
##
##
JAVA_HOME=/usr/java/jre1.5.0_16
NLS_LANG=JAPANESE_JAPAN.AL32UTF8
ORACLE_HOME=/opt/app/oracle/product/10.2.0/db
orcl=${orcl_HHN001}
