#_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
# 変数の定義
#_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
##
#DDC#LOG_DIR=/wk_apl/apl/wk002/hnad/log
LOG_DIR=/prod/LAWSON/LOG
LOG_BASE=$(basename $0)
LOG_FILE=${LOG_DIR}/${LOG_BASE}.log.`date +%m%d`

#_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
# 同一日のLOG_FILEが存在する場合はリネームして保存
#_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
##
if [ -f ${LOG_FILE} ]; then
    # 現在月とファイル月を取得
    r_month=`date +%b`
    f_month=(`ls -l ${LOG_FILE}`)
    # 当日のログが存在する場合はリネームして待避する
    if [ ${r_month} = ${f_month[5]} ]; then
        log_ext=`date +%H%M`
        /bin/mv ${LOG_FILE} ${LOG_FILE}.${log_ext}
        /bin/touch ${LOG_FILE}
        echo "${LOG_BASE} : 旧ログを保存しました。 ${LOG_FILE}.${log_ext}" | tee -a ${LOG_FILE}
    fi
fi
unset r_month
unset f_month

echo "${LOG_BASE} : ログファイル名＝ ${LOG_FILE}" | tee -a ${LOG_FILE}

### ログの削除は「CLEAR.DAY.SYSTEMMENTE」で実施するので、削除
### #①findコマンドで90日以前の対象ログファイルをリスト化する
### list=(`find ${LOG_DIR} -name "${LOG_BASE}.log.*" -a ! -mtime -90 -a -type f -print`)
### #②対象を全部削除するまでループする
### for CHKLOG in "${list[@]}"; do
###     echo -n "${LOG_BASE} : [旧ログ削除]" | tee -a ${LOG_FILE}
###     echo `ls -l ${CHKLOG} |gawk '{printf("%-33s %s%s %s\n",$9,$6,$7,$8)}'` | tee -a ${LOG_FILE}
###     /bin/rm ${CHKLOG}
### done
### unset list

#開始メッセージサンプル
#echo "${LOG_BASE} : start time = `date +%y/%m/%d:%H:%M:%S`" | tee -a ${LOG_FILE}
#終了メッセージサンプル
#echo "${LOG_BASE} : end time : `date +%y/%m/%d:%H:%M:%S`" | tee -a ${LOG_FILE}
#エラーメッセージサンプル
#echo "${LOG_BASE} : ABEND end : `date +%y/%m/%d:%H:%M:%S`" | tee -a ${LOG_FILE}

