 USING INDEX 
 TABLESPACE USERTBS1 NOLOGGING PCTFREE 10 INITRANS 2  MAXTRANS 255 
 STORAGE  (INITIAL 1M NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0
 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
)
);
