LOAD DATA
 APPEND INTO TABLE HNT_オンライン宛先ベンダー
 (
 チェーンストアコード                     POSITION(1:4) CHAR,
 宛先コード                               POSITION(5:12) CHAR,
 ベンダーコード                           POSITION(13:18) CHAR,
 ベンダー営業所コード                     POSITION(19:20) CHAR,
 テストフラグ                             POSITION(21:22) CHAR,
 有効終了日                               POSITION(23:30) DATE "YYYYMMDD",
 有効開始日                               POSITION(31:38) DATE "YYYYMMDD",
 配信種別４０コピーフラグ                 POSITION(39:40) CHAR,
 配信種別５０コピーフラグ                 POSITION(41:42) CHAR,
 コピー１チェーンストアコード             POSITION(43:46) CHAR,
 コピー１宛先コード                       POSITION(47:54) CHAR,
 コピー１センターコード                   POSITION(55:56) CHAR,
 配信種別４０コピー１フラグ               POSITION(57:58) CHAR,
 配信種別５０コピー１フラグ               POSITION(59:60) CHAR,
 コピー２チェーンストアコード             POSITION(61:64) CHAR,
 コピー２宛先コード                       POSITION(65:72) CHAR,
 コピー２センターコード                   POSITION(73:74) CHAR,
 配信種別４０コピー２フラグ               POSITION(75:76) CHAR,
 配信種別５０コピー２フラグ               POSITION(77:78) CHAR,
 くくりＶＤＲコード                       POSITION(79:84) CHAR,
 ＤＤＣ宛先コード                         POSITION(85:92) CHAR,
 ＤＤＣベンダーコード                     POSITION(93:98) CHAR,
 実績配信有無フラグ                       POSITION(99:100) CHAR,
 処理区分                                 POSITION(101:102) CHAR,
 物理削除日                               POSITION(103:110) DATE "YYYYMMDD",
 コピー処理日                             POSITION(111:118) DATE "YYYYMMDD",
 コピー処理状況区分                       POSITION(119:120) CHAR,
 物理削除区分                             POSITION(121:122) CHAR,
 作成者氏名コード                         POSITION(123:130) CHAR,
 作成者氏名                               POSITION(131:160) CHAR,
 作成者部署コード                         POSITION(161:166) CHAR,
 作成者部署名                             POSITION(167:206) CHAR,
 作成プログラムＩＤ                       POSITION(207:246) CHAR,
 作成日時                                 POSITION(247:260) DATE "YYYYMMDDHH24MISS",
 オンライン更新者氏名コード               POSITION(261:268) CHAR,
 オンライン更新者氏名                     POSITION(269:298) CHAR,
 オンライン更新者部署コード               POSITION(299:304) CHAR,
 オンライン更新者部署名                   POSITION(305:344) CHAR,
 オンライン更新プログラムＩＤ             POSITION(345:384) CHAR,
 オンライン更新日時                       POSITION(385:398) DATE "YYYYMMDDHH24MISS",
 バッチ更新プログラムＩＤ                 POSITION(399:438) CHAR,
 バッチ更新日時                           POSITION(439:452) DATE "YYYYMMDDHH24MISS",
 ロック連番                               POSITION(453:456) ZONED NULLIF ロック連番=BLANKS,
 削除区分                                 POSITION(457:458) CHAR,
 更新端末ＩＤ                             POSITION(459:488) CHAR
 )
