LOAD DATA
 APPEND INTO TABLE HNT_新オンライン宛先ベンダー
 (
 チェーンストアコード                     POSITION(1:4) CHAR,
 宛先コード                               POSITION(5:12) CHAR,
 ベンダーコード                           POSITION(13:18) CHAR,
 ベンダー営業所コード                     POSITION(19:20) CHAR,
 通番                                     POSITION(21:23) ZONED NULLIF 通番=BLANKS,
 有効終了日                               POSITION(24:31) DATE "YYYYMMDD",
 有効開始日                               POSITION(32:39) DATE "YYYYMMDD",
 コピーチェーンストアコード               POSITION(40:43) CHAR,
 コピー宛先コード                         POSITION(44:51) CHAR,
 コピーセンターコード                     POSITION(52:53) CHAR,
 実績配信有無フラグ                       POSITION(54:55) CHAR,
 有効フラグ                               POSITION(56:57) CHAR,
 処理区分                                 POSITION(58:59) CHAR,
 物理削除日                               POSITION(60:67) DATE "YYYYMMDD",
 コピー処理日                             POSITION(68:75) DATE "YYYYMMDD",
 コピー処理状況区分                       POSITION(76:77) CHAR,
 物理削除区分                             POSITION(78:79) CHAR,
 作成者氏名コード                         POSITION(80:87) CHAR,
 作成者氏名                               POSITION(88:117) CHAR,
 作成者部署コード                         POSITION(118:123) CHAR,
 作成者部署名                             POSITION(124:163) CHAR,
 作成プログラムＩＤ                       POSITION(164:203) CHAR,
 作成日時                                 POSITION(204:217) DATE "YYYYMMDDHH24MISS",
 オンライン更新者氏名コード               POSITION(218:225) CHAR,
 オンライン更新者氏名                     POSITION(226:255) CHAR,
 オンライン更新者部署コード               POSITION(256:261) CHAR,
 オンライン更新者部署名                   POSITION(262:301) CHAR,
 オンライン更新プログラムＩＤ             POSITION(302:341) CHAR,
 オンライン更新日時                       POSITION(342:355) DATE "YYYYMMDDHH24MISS",
 バッチ更新プログラムＩＤ                 POSITION(356:395) CHAR,
 バッチ更新日時                           POSITION(396:409) DATE "YYYYMMDDHH24MISS",
 ロック連番                               POSITION(410:413) ZONED NULLIF ロック連番=BLANKS,
 削除区分                                 POSITION(414:415) CHAR,
 更新端末ＩＤ                             POSITION(416:445) CHAR
 )
