LOAD DATA
 APPEND INTO TABLE HNT_ベンダー別計画終了対象商品
 (
 商品コード                               POSITION(1:13)    CHAR,
 ベンダーコード                           POSITION(14:19)   CHAR,
 有効終了日                               POSITION(20:27)   CHAR,
 有効開始日                               POSITION(28:35)   CHAR,
 社コード                                 POSITION(36:41)   CHAR,
 配送センターベンダーコード               POSITION(42:47)   CHAR,
 推奨取消案内週                           POSITION(48:52)   ZONED NULLIF 推奨取消案内週=BLANKS,
 保護期間開始日                           POSITION(53:60)   CHAR,
 保護期間終了日                           POSITION(61:68)   CHAR,
 計画終了有効開始日                       POSITION(69:76)   CHAR,
 計画終了有効終了日                       POSITION(77:84)   CHAR,
 不可日設定日                             POSITION(85:92)   CHAR,
 不可日終了日                             POSITION(93:100)  CHAR,
 推奨取消日                               POSITION(101:108) CHAR,
 処理区分                                 POSITION(109:110) CHAR,
 物理削除日                               POSITION(111:118) CHAR,
 コピー処理日                             POSITION(119:126) CHAR,
 コピー処理状況区分                       POSITION(127:128) CHAR,
 物理削除区分                             POSITION(129:130) CHAR,
 作成者氏名コード                         POSITION(131:138) CHAR,
 作成者氏名                               POSITION(139:168) CHAR,
 作成者部署コード                         POSITION(169:174) CHAR,
 作成者部署名                             POSITION(175:214) CHAR,
 作成プログラムＩＤ                       POSITION(215:254) CHAR,
 作成日時                                 POSITION(255:268) DATE "YYYYMMDDHH24MISS",
 オンライン更新者氏名コード               POSITION(269:276) CHAR,
 オンライン更新者氏名                     POSITION(277:306) CHAR,
 オンライン更新者部署コード               POSITION(307:312) CHAR,
 オンライン更新者部署名                   POSITION(313:352) CHAR,
 オンライン更新プログラムＩＤ             POSITION(353:392) CHAR,
 オンライン更新日時                       POSITION(393:406) DATE "YYYYMMDDHH24MISS",
 バッチ更新プログラムＩＤ                 POSITION(407:446) CHAR,
 バッチ更新日時                           POSITION(447:460) DATE "YYYYMMDDHH24MISS",
 ロック連番                               POSITION(461:464) ZONED NULLIF ロック連番=BLANKS,
 削除区分                                 POSITION(465:466) CHAR,
 更新端末ＩＤ                             POSITION(467:496) CHAR
 )
