LOAD DATA
 APPEND INTO TABLE HNT_社別商品
 (
 商品コード                               POSITION(1:13) CHAR,
 社コード                                 POSITION(14:19) CHAR,
 有効終了日                               POSITION(20:27) DATE "YYYYMMDD",
 有効開始日                               POSITION(28:35) DATE "YYYYMMDD",
 初回有効開始日                           POSITION(36:43) DATE "YYYYMMDD",
 商品名                                   POSITION(44:87) CHAR
  "DECODE(RTRIM(RTRIM(:商品名),'　'),NULL,'　',RTRIM(RTRIM(:商品名),'　'))",
 商品名カナ                               POSITION(88:109) CHAR
  "DECODE(RTRIM(RTRIM(:商品名カナ),'　'),NULL,'　',RTRIM(RTRIM(:商品名カナ),'　'))",
 商品名用納品日                           POSITION(110:119) CHAR,
 商品名用納品日カナ                       POSITION(120:124) CHAR,
 非商品区分                               POSITION(125:126) CHAR,
 レシート表示用名                         POSITION(127:148) CHAR
  "DECODE(RTRIM(RTRIM(:レシート表示用名),'　'),NULL,'　',RTRIM(RTRIM(:レシート表示用名),'　'))",
 ケースラベル名                           POSITION(149:228) CHAR,
 ＪＡＮコード                             POSITION(229:241) CHAR,
 ＪＡＮ区分                               POSITION(242:243) CHAR,
 入力元ＪＡＮコード                       POSITION(244:256) CHAR,
 ダミーＪＡＮコード使用フラグ             POSITION(257:258) CHAR,
 メーカーコード                           POSITION(259:264) CHAR,
 ＤＥＰＴコード                           POSITION(265:267) CHAR,
 ＣＬＡＳＳコード                         POSITION(268:270) CHAR,
 ＳＵＢＣＬＡＳＳコード                   POSITION(271:273) CHAR,
 商品業態区分                             POSITION(274:275) CHAR,
 ＮＯＮＰＬＵ価格５桁区分                 POSITION(276:277) CHAR,
 単品セット区分                           POSITION(278:279) CHAR,
 シェル区分                               POSITION(280:281) CHAR,
 シェル収納本数                           POSITION(282:285) ZONED NULLIF シェル収納本数=BLANKS,
 ライセンス種別                           POSITION(286:287) CHAR,
 ＬＯＰＰＩ取扱フラグ                     POSITION(288:289) CHAR,
 全国一律原価本体金額                     POSITION(290:297) ZONED(8,2) NULLIF 全国一律原価本体金額=BLANKS,
 全国一律原価税込金額                     POSITION(298:305) ZONED(8,2) NULLIF 全国一律原価税込金額=BLANKS,
 全国一律原価税金額                       POSITION(306:313) ZONED(8,2) NULLIF 全国一律原価税金額=BLANKS,
 全国一律売価本体金額                     POSITION(314:319) ZONED NULLIF 全国一律売価本体金額=BLANKS,
 全国一律売価税込金額                     POSITION(320:325) ZONED NULLIF 全国一律売価税込金額=BLANKS,
 全国一律売価税金額                       POSITION(326:331) ZONED NULLIF 全国一律売価税金額=BLANKS,
 シェル原価                               POSITION(332:339) ZONED(8,2) NULLIF シェル原価=BLANKS,
 シェル売価                               POSITION(340:345) ZONED NULLIF シェル売価=BLANKS,
 原材料容量                               POSITION(346:352) ZONED(7,2) NULLIF 原材料容量=BLANKS,
 内容量区分                               POSITION(353:354) CHAR,
 原材料区分                               POSITION(355:356) CHAR,
 在庫引当フラグ                           POSITION(357:358) CHAR,
 売価変更指示対象外フラグ                 POSITION(359:360) CHAR,
 通常予約発注フラグ                       POSITION(361:362) CHAR,
 包材区分                                 POSITION(363:364) CHAR,
 デザインパッケージ変更区分               POSITION(365:366) CHAR,
 日販即売雑誌返品先区分                   POSITION(367:368) CHAR,
 沖縄即売雑誌返品先区分                   POSITION(369:370) CHAR,
 即売雑誌販売期間日数                     POSITION(371:373) ZONED NULLIF 即売雑誌販売期間日数=BLANKS,
 即売雑誌発行形態区分                     POSITION(374:375) CHAR,
 年契メーカーコード                       POSITION(376:381) CHAR,
 新聞社出版社コード                       POSITION(382:387) CHAR,
 商品格付区分                             POSITION(388:389) CHAR,
 入荷許容期間基準区分                     POSITION(390:391) CHAR,
 入荷許容期間年月日区分                   POSITION(392:393) CHAR,
 入荷許容期間                             POSITION(394:396) ZONED NULLIF 入荷許容期間=BLANKS,
 販売許容期間基準区分                     POSITION(397:398) CHAR,
 販売許容期間年月日区分                   POSITION(399:400) CHAR,
 販売許容期間                             POSITION(401:403) ZONED NULLIF 販売許容期間=BLANKS,
 最大発注数                               POSITION(404:408) ZONED NULLIF 最大発注数=BLANKS,
 新店発注数                               POSITION(409:413) ZONED NULLIF 新店発注数=BLANKS,
 陳列傾斜区分                             POSITION(414:415) CHAR,
 縦長さ                                   POSITION(416:420) ZONED(5,1) NULLIF 縦長さ=BLANKS,
 横長さ                                   POSITION(421:425) ZONED(5,1) NULLIF 横長さ=BLANKS,
 奥長さ                                   POSITION(426:430) ZONED(5,1) NULLIF 奥長さ=BLANKS,
 消費税区分                               POSITION(431:432) CHAR,
 不課税扱い有無フラグ                     POSITION(433:434) CHAR,
 採用区分                                 POSITION(435:436) CHAR,
 ＰＣ出力区分                             POSITION(437:438) CHAR,
 陳列数                                   POSITION(439:440) ZONED NULLIF 陳列数=BLANKS,
 ＯＢ重点フラグ                           POSITION(441:442) CHAR,
 クレジット不可区分                       POSITION(443:444) CHAR,
 発注不可フラグ                           POSITION(445:446) CHAR,
 販売不可フラグ                           POSITION(447:448) CHAR,
 ＮＢＰＢ区分                             POSITION(449:450) CHAR,
 ＱＵＯカード決済不可フラグ               POSITION(451:452) CHAR,
 ＱＵＯ受託品フラグ                       POSITION(453:454) CHAR,
 ＳＳＩ特殊商品区分                       POSITION(455:456) CHAR,
 商品撮影依頼番号                         POSITION(457:462) CHAR,
 ＴＶＣＭ区分                             POSITION(463:464) CHAR,
 初回導入条件                             POSITION(465:504) CHAR,
 変更取消理由説明                         POSITION(505:534) CHAR,
 マルチメディア共通管理１                 POSITION(535:544) ZONED NULLIF マルチメディア共通管理１=BLANKS,
 マルチメディア共通管理２                 POSITION(545:554) ZONED NULLIF マルチメディア共通管理２=BLANKS,
 入力依頼者氏名コード                     POSITION(555:562) CHAR,
 入力依頼者氏名                           POSITION(563:582) CHAR,
 処理区分                                 POSITION(583:584) CHAR,
 物理削除日                               POSITION(585:592) DATE "YYYYMMDD",
 コピー処理日                             POSITION(593:600) DATE "YYYYMMDD",
 コピー処理状況区分                       POSITION(601:602) CHAR,
 物理削除区分                             POSITION(603:604) CHAR,
 作成者氏名コード                         POSITION(605:612) CHAR,
 作成者氏名                               POSITION(613:642) CHAR,
 作成者部署コード                         POSITION(643:648) CHAR,
 作成者部署名                             POSITION(649:688) CHAR,
 作成プログラムＩＤ                       POSITION(689:728) CHAR,
 作成日時                                 POSITION(729:742) DATE "YYYYMMDDHH24MISS",
 オンライン更新者氏名コード               POSITION(743:750) CHAR,
 オンライン更新者氏名                     POSITION(751:780) CHAR,
 オンライン更新者部署コード               POSITION(781:786) CHAR,
 オンライン更新者部署名                   POSITION(787:826) CHAR,
 オンライン更新プログラムＩＤ             POSITION(827:866) CHAR,
 オンライン更新日時                       POSITION(867:880) DATE "YYYYMMDDHH24MISS",
 バッチ更新プログラムＩＤ                 POSITION(881:920) CHAR,
 バッチ更新日時                           POSITION(921:934) DATE "YYYYMMDDHH24MISS",
 ロック連番                               POSITION(935:938) ZONED NULLIF ロック連番=BLANKS,
 削除区分                                 POSITION(939:940) CHAR,
 更新端末ＩＤ                             POSITION(941:970) CHAR
 )
